version: "3.2"

services:
  elasticsearch:
    build:
      context: "${PWD}/elasticsearch/"
      dockerfile: Dockerfile
    volumes:
      - type: bind
        # 복사할 파일의 위치
        source: "${PWD}/elasticsearch/config/elasticsearch.yml"
        # 컨테이너 속 위치
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - "${PWD}/elasticsearch/data:/var/lib/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
    networks:
      - efk

  fluentd:
    build:
      context: "${PWD}/fluentd/"
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "${PWD}/fluentd/conf"
        target: /fluentd/etc
        read_only: true
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
    networks:
      - efk

  kibana:
    build:
      context: kibana/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: "${PWD}/kibana/config/kibana.yml"
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch

networks:
  efk:
    driver: bridge
